[workspace]
resolver = "2"
members = ["am4", "am4-app", "am4-web", "misc/scripts/prepare_data"]

[profile.release]
debug = true

[profile.wasm-release]
inherits = "release"
opt-level = 's'
lto = true
codegen-units = 1
