[package]
name = "am4-app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
am4 = { path = "../am4" }
eframe = { version = "0.27.2", features = ["default", "__screenshot"] }
once_cell = "1.19.0"
