[package]
name = "am4"
version = "0.2.0"
authors = ["Abraham Cheung <abraham@ylcheung.com>"]
edition = "2021"

[dependencies]
csv = "1.3.0"
jaro_winkler = "0.1.0"
serde = { version = "1.0.203", features = ["derive"] }
thiserror = "1.0.61"
